[metadata]
name = "{{PACK_NAME}}"
description = "Atlas starter template"

[versions]
mc = "1.21.11"
modloader = "neoforge"
modloader_version = "21.11.38-beta"

[cli]
pack_id = "{{PACK_ID}}"
default_channel = "dev"

