source = "modrinth"
project_id = "AANobbMI"
version = "mc1.21.11-0.8.4-neoforge"
download_url = "https://cdn.modrinth.com/data/AANobbMI/versions/B0QEOpLx/sodium-neoforge-0.8.4%2Bmc1.21.11.jar"

[metadata]
name = "Sodium"

[hashes]
sha512 = "677ed5d1126cca5a5e303e84f0bc9794e72e7312df228b413645de048f8aac3dccca0cc4145ca1005e20f44ab720505273d08848ec239d15c26029ae637900f2"
